# Generated by Django 3.0.3 on 2020-06-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200519_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
    ]
