# Generated by Django 3.0.3 on 2020-05-20 16:39

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.user_directory_path),
        ),
    ]
