# Generated by Django 3.0.3 on 2020-06-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_auto_20200602_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercomment',
            name='user',
        ),
    ]
