# Generated by Django 3.0.3 on 2020-05-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0003_auto_20200519_2132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('shiped', 'Shiped'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='processing', max_length=256)),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('payment_data', models.DateTimeField(blank=True, null=True)),
                ('manager', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery', models.CharField(choices=[('own', 'own pickup'), ('DHL', 'DHL'), ('New_Post', 'New Post')], max_length=256)),
                ('filial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'unique_together': {('order', 'item')},
            },
        ),
    ]
