# Generated by Django 3.0.3 on 2020-05-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200531_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='suma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
