# Generated by Django 3.0.3 on 2020-05-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_promocodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocodes',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
